# A string used to distinguish different Supabase projects on the same host. Used by the CLI for local link state.
project_id = "fvgollhjkvkxmibqksgv"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://www.centuriesmutual.com"
additional_redirect_urls = [
  "https://www.centuriesmutual.com/auth/callback",
  "https://www.centuriesmutual.com/auth/update-password",
  "https://centuriesmutual.com/auth/callback",
  "https://centuriesmutual.com/auth/update-password",
  "http://localhost:3030/auth/callback",
  "http://localhost:3030/auth/update-password"
]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = true

[storage]
enabled = true
