import type { YtVideo } from '@/lib/youtube/types'

/** Seed catalog used until YOUTUBE_API_KEY is set on Vercel. */
export const YT_CATALOG: ReadonlyArray<YtVideo> = [
  {
    id: 'dQw4w9WgXcQ',
    title: 'Centuries Mutual — Member orientation walkthrough',
    description:
      'A guided overview of membership, wallet rewards, and how coverage pathways work together.',
    channelId: 'cm-official',
    channelTitle: 'Centuries Mutual',
    channelAvatar: '/cmlogotreesmall-removebg-preview.png',
    thumbnail: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    duration: '3:32',
    durationSeconds: 212,
    viewCount: 12840,
    publishedAt: '2026-06-02T14:00:00.000Z',
    tags: ['orientation', 'membership', 'wallet'],
    category: 'For you',
  },
  {
    id: '9bZkp7q19f0',
    title: 'Understanding Medicare Advantage enrollment periods',
    description: 'AEP, OEP, IEP, and SEP explained for members comparing Advantage options.',
    channelId: 'cm-medicare',
    channelTitle: 'CM Medicare Desk',
    channelAvatar: '/cmlogotreesmall-removebg-preview.png',
    thumbnail: 'https://i.ytimg.com/vi/9bZkp7q19f0/hqdefault.jpg',
    duration: '8:14',
    durationSeconds: 494,
    viewCount: 9421,
    publishedAt: '2026-05-18T10:00:00.000Z',
    tags: ['medicare', 'advantage', 'enrollment'],
    category: 'Medicare',
  },
  {
    id: 'kJQP7kiw5Fk',
    title: 'My Brothers Keeper — weekly streak habits',
    description: 'Short movement sessions that sync wellness rewards into your ledger.',
    channelId: 'cm-mbk',
    channelTitle: 'My Brothers Keeper',
    channelAvatar: '/cmlogotreesmall-removebg-preview.png',
    thumbnail: 'https://i.ytimg.com/vi/kJQP7kiw5Fk/hqdefault.jpg',
    duration: '5:01',
    durationSeconds: 301,
    viewCount: 22014,
    publishedAt: '2026-07-01T16:30:00.000Z',
    tags: ['wellness', 'mbk', 'fitness'],
    category: 'Wellness',
  },
  {
    id: 'fJ9rUzIMcZQ',
    title: 'Wintergarden conservatory — first rehearsal',
    description: 'How daily tokens unlock scored performance sessions in Wintergarden.',
    channelId: 'cm-wintergarden',
    channelTitle: 'Wintergarden',
    channelAvatar: '/cmlogotreesmall-removebg-preview.png',
    thumbnail: 'https://i.ytimg.com/vi/fJ9rUzIMcZQ/hqdefault.jpg',
    duration: '11:20',
    durationSeconds: 680,
    viewCount: 6702,
    publishedAt: '2026-04-22T12:00:00.000Z',
    tags: ['wintergarden', 'music', 'tokens'],
    category: 'Music',
  },
  {
    id: '3JZ_D3ELwOQ',
    title: 'ACA Individual & Family — what to prepare',
    description: 'Household size, income estimates, and documents for marketplace-style enrollment.',
    channelId: 'cm-enrollment',
    channelTitle: 'CM Enrollment',
    channelAvatar: '/cmlogotreesmall-removebg-preview.png',
    thumbnail: 'https://i.ytimg.com/vi/3JZ_D3ELwOQ/hqdefault.jpg',
    duration: '6:48',
    durationSeconds: 408,
    viewCount: 5109,
    publishedAt: '2026-03-11T09:00:00.000Z',
    tags: ['aca', 'family', 'enrollment'],
    category: 'Enrollment',
  },
  {
    id: 'OPf0YbXqDm0',
    title: 'Cash Out — Coinbase & Robinhood linking',
    description: 'Connect OAuth destinations and move rewards cash when balances post.',
    channelId: 'cm-wallet',
    channelTitle: 'CM Wallet',
    channelAvatar: '/cmlogotreesmall-removebg-preview.png',
    thumbnail: 'https://i.ytimg.com/vi/OPf0YbXqDm0/hqdefault.jpg',
    duration: '4:05',
    durationSeconds: 245,
    viewCount: 3890,
    publishedAt: '2026-06-28T18:00:00.000Z',
    tags: ['wallet', 'cashout', 'oauth'],
    category: 'Wallet',
  },
  {
    id: 'RgKAFK5djSk',
    title: 'Paying utilities with Paymentus',
    description: 'Bill pay for electric, water, and gas from eligible rewards cash.',
    channelId: 'cm-wallet',
    channelTitle: 'CM Wallet',
    channelAvatar: '/cmlogotreesmall-removebg-preview.png',
    thumbnail: 'https://i.ytimg.com/vi/RgKAFK5djSk/hqdefault.jpg',
    duration: '3:55',
    durationSeconds: 235,
    viewCount: 2744,
    publishedAt: '2026-05-02T15:00:00.000Z',
    tags: ['utilities', 'paymentus', 'wallet'],
    category: 'Wallet',
  },
  {
    id: '60ItHLz5WEA',
    title: 'Find a Provider — network search tips',
    description: 'Search by specialty and ZIP to locate in-network clinicians.',
    channelId: 'cm-care',
    channelTitle: 'CM Care Access',
    channelAvatar: '/cmlogotreesmall-removebg-preview.png',
    thumbnail: 'https://i.ytimg.com/vi/60ItHLz5WEA/hqdefault.jpg',
    duration: '7:12',
    durationSeconds: 432,
    viewCount: 8011,
    publishedAt: '2026-02-19T11:00:00.000Z',
    tags: ['provider', 'network', 'care'],
    category: 'Care',
  },
  {
    id: 'hT_nvWreIhg',
    title: 'Compound interest pathway overview',
    description: 'How legacy allocations relate to long-horizon member rewards.',
    channelId: 'cm-legacy',
    channelTitle: 'CM Legacy',
    channelAvatar: '/cmlogotreesmall-removebg-preview.png',
    thumbnail: 'https://i.ytimg.com/vi/hT_nvWreIhg/hqdefault.jpg',
    duration: '9:40',
    durationSeconds: 580,
    viewCount: 4560,
    publishedAt: '2026-01-30T13:00:00.000Z',
    tags: ['compound', 'legacy', 'rewards'],
    category: 'Legacy',
  },
  {
    id: 'e-ORhEE9VVg',
    title: 'Dental benefits — preventive vs restorative',
    description: 'What to expect when adding dental coverage to your membership.',
    channelId: 'cm-enrollment',
    channelTitle: 'CM Enrollment',
    channelAvatar: '/cmlogotreesmall-removebg-preview.png',
    thumbnail: 'https://i.ytimg.com/vi/e-ORhEE9VVg/hqdefault.jpg',
    duration: '5:33',
    durationSeconds: 333,
    viewCount: 3320,
    publishedAt: '2026-04-05T17:00:00.000Z',
    tags: ['dental', 'enrollment', 'benefits'],
    category: 'Enrollment',
  },
  {
    id: 'YQHsXMglC9A',
    title: 'Group plans for employers — first steps',
    description: 'Employer sponsorship fields and effective date planning for groups.',
    channelId: 'cm-group',
    channelTitle: 'CM Group Plans',
    channelAvatar: '/cmlogotreesmall-removebg-preview.png',
    thumbnail: 'https://i.ytimg.com/vi/YQHsXMglC9A/hqdefault.jpg',
    duration: '6:02',
    durationSeconds: 362,
    viewCount: 1988,
    publishedAt: '2026-03-27T08:00:00.000Z',
    tags: ['group', 'employer', 'enrollment'],
    category: 'Enrollment',
  },
  {
    id: '2Vv-BfVoq4g',
    title: 'Member stories — rewards for rent and groceries',
    description: 'How healthcare rewards cash can settle everyday eligible expenses.',
    channelId: 'cm-official',
    channelTitle: 'Centuries Mutual',
    channelAvatar: '/cmlogotreesmall-removebg-preview.png',
    thumbnail: 'https://i.ytimg.com/vi/2Vv-BfVoq4g/hqdefault.jpg',
    duration: '4:44',
    durationSeconds: 284,
    viewCount: 15420,
    publishedAt: '2026-06-14T20:00:00.000Z',
    tags: ['rewards', 'pay', 'stories'],
    category: 'For you',
  },
]

export const YT_CATEGORIES = [
  'All',
  'For you',
  'Enrollment',
  'Medicare',
  'Wellness',
  'Music',
  'Wallet',
  'Care',
  'Legacy',
] as const

export function getCatalogVideo(id: string) {
  return YT_CATALOG.find((v) => v.id === id) ?? null
}
